services:
  nginx-proxy:
    container_name: nginx-proxy
    image: nginx:latest
    volumes:
      - ./volume/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 5116:80
    depends_on:
      - crawling_api
      - crawling_dashboard
  crawling_db:
    image: mongo
    container_name: crawling_db
    volumes:
      - ./volume/mongodb/data:/data/db
    expose:
      - 27017
    restart: always
  crawling_api:
    image: taeng0204/go-api
    container_name: crawling_api
    expose:
      - 8000
    depends_on:
      - crawling_db
  crawling_dashboard:
    image: taeng0204/dashboard
    container_name: crawling_dashboard
    expose:
      - 8888
  melon_boygroup_crawling:
    image: taeng0204/crawling
    container_name: melon_boygroup
    environment:
      - FILE_NAME=melon_boygroup.py
      - TZ=Asia/Seoul
    volumes:
      - ./app:/usr/src/app
      - ./requirements.txt:/usr/src/requirements.txt
  melon_girlgroup_crawling:
    image: taeng0204/crawling
    container_name: melon_girlgroup
    environment:
      - FILE_NAME=melon_girlgroup.py
      - TZ=Asia/Seoul
    volumes:
      - ./app:/usr/src/app
      - ./requirements.txt:/usr/src/requirements.txt
  youtube_crawling:
    image: taeng0204/crawling
    container_name: youtube_crawling
    environment:
      - FILE_NAME=youtube.py
      - TZ=Asia/Seoul
    volumes:
      - ./app:/usr/src/app
      - ./requirements.txt:/usr/src/requirements.txt