services:
  crawling_db:
    image: mongo
    container_name: crawling_db
    volumes:
      - ./volume/mongodb/data:/data/db
    expose:
      - 27017
    restart: always
  crawling-exmaple:
    image: taeng0204/crawling-example
    container_name: crawling-exmaple

      