services:
  example_crawling:
    image: taeng0204/crawling
    container_name: example_crawling
    environment:
      - FILE_NAME=example.py
    depends_on:
      - crawling_db
    networks:
      default_bridge:
        ipv4_address: 172.19.0.3
    restart: always
  melon_example_crawling:
    image: taeng0204/crawling
    container_name: melon_example_crawling
    environment:
      - FILE_NAME=melon_example.py
    depends_on:
      - crawling_db
    networks:
      default_bridge:
        ipv4_address: 172.19.0.4
    restart: always
  crawling_db:
    image: mongo
    container_name: crawling_db
    volumes:
      - ./volume/mongodb/data:/data/db
    ports:
      - 27017:27017
    networks:
      default_bridge:
        ipv4_address: 172.19.0.2
    restart: always
networks:
  default_bridge:
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16