name: Deploy

on:
  push:
    paths:
      - 'app/**'
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: ssh conection
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/${{ secrets.USERNAME }}/Desktop/LLOYDK-Crawler
          git pull
          docker compose up -d
