name: Build and Push Docker Images

on:
  push:
    branches: [ main ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Get File List
      id: file_list
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.MY_GITHUB_TOKEN }}
        script: |
          const response = await github.rest.repos.getContent({
            owner: context.repo.owner,
            repo: context.repo.repo,
            path: 'app'
          });
          const fileNames = response.data.map((file) => file.name);
          console.log(fileNames);
          core.setOutput("files", fileNames);
          
    - name: Build and Push Docker Images
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        echo "file names: ${{ steps.file_list.outputs.files }}" 
        for file in ${${{ steps.file_list.outputs.files }}//[\[\],\']/}; do
          echo "current file: $file"
          IMAGE_NAME="***/${file%.*}"
          docker build -t $IMAGE_NAME --build-arg FILE_NAME=$file .
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
          docker push $IMAGE_NAME
        done
        
