name: Deploy

on:
  push:
    paths:
      - 'app/**.py'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Git pull
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} -p 5115 "cd /path/to/repository && git pull"

      - name: Docker Compose up
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} -p 5115 "cd /path/to/repository && docker compose up -d"
